services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-mypassword}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_DB: ${DB_NAME:-tasks}
    container_name: ${DB_CONTAINER:-task-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9001}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8901}:8900'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-sail}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    volumes:
      - 'sail-data:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
    networks:
      - app-network

volumes:
  postgres_data:
  sail-data:
    driver: local

networks:
  app-network:
    driver: bridge
