export enum PermissionsEnum {
  CREATE_OWN_TASK = 'CREATE_TASK',
  READ_ALL_OWN_TASK = 'READ_OWN_ALL_TASK',
  READ_OWN_TASK = 'READ_TASK',
  UPDATE_OWN_TASK = 'UPDATE_TASK',
  DELETE_OWN_TASK = 'DELETE_TASK',
  READ_ALL_TASK = 'READ_ALL_TASK',
  UPDATE_ALL_TASK = 'UPDATE_ALL_TASK',
  DELETE_ALL_TASK = 'DELETE_ALL_TASK',
}
